language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install: pip install -r requirements-test.txt --use-mirrors
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB;" -U postgres
script: ./run-tests.sh
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
        - tneale@sunlightfoundation.com
        - paultag@sunlightfoundation.com
