language: python
addons:
    postgresql: "9.4"
    apt:
        packages:
            - "postgresql-9.4-postgis-2.3"
sudo: false
python:
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=">=1.11,<2"
    - DJANGO_VERSION="2.0a1"
install:
    - pip install .[dev] --pre Django$DJANGO_VERSION
    - pip install -e git+https://github.com/opencivicdata/python-opencivicdata.git#egg=opencivicdata
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
  - ./run-tests.sh
  - flake8 pupa
after_success:
    - coveralls
notifications:
    email:
        - james@openstates.org
