language: python
addons:
    postgresql: "9.4"
sudo: false
python:
    - "3.4"
    - "3.5"
install: pip install -r requirements-test.txt
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: ./run-tests.sh
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
